### ISSUE TITLE
a loooot of errors on every page

### ISSUE THREAD

**Issue by pavelbat3** [Hostname47/PHP_ENCRYPTED_CHAT#10]
![image](https://github.com/Hostname47/PHP-CHAT/assets/99824228/cd175fd1-39d8-4da4-b134-5dc66461500a)
![image](https://github.com/Hostname47/PHP-CHAT/assets/99824228/badf9df6-f1f2-4a3e-a0aa-f82fadc75924)
![image](https://github.com/Hostname47/PHP-CHAT/assets/99824228/dfc3dee9-e722-4c64-9e97-11cd17d09762)

**Comment by Hostname47** [comment]
The problems above are because of the wrong PHP version, please use the same version as in the video, I think it's PHP 7.2 as far as I can remember

**Comment by pavelbat3** [comment]
> The problems above are because of the wrong PHP version, please use the same version as in the video, I think it's PHP 7.2 as far as I can remember

thanks, i will try it
